- name: Create Production VM
  hosts: localhost
  connection: local

  vars:
   myResourceGroup: devopscw2
   myVnet: devopscw2-node-vnet
   mySubnet: devopscw2-node-subnet
   myPublicIP: devopscw2-node-publicip
   myNIC: devopscw2-node-nic
   myNetworkSecurityGroup: devopscw2-node-nsg
   myVM: devopscw2-node
   mySSHkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClJeod6S4L1Hcx5aHtrL47mM/btvrl3XMP/m9nyQEl980FsrF+JD/hc3PVJVHN3MwT9aAP1fJgw2wuLHHe4BP90MTOAbtUWjpkcvKgj4mWOrfMBj/rTCuu74ps8WUxaZz8aeAVVu1cGr3hn38ZxWR4XynxelXDEJkVUKHOFhvf48skmJ29vPMEAOXqcayjMAqkzKnI7VyM21cIHSwzy7rSnLcv+bRSYuAIVkj7TMdlKf0Npj5srTyaxxHjDFGw1q4ZpnR5ORwu7btUhjUFAJ2p6C8zpEdauCI1fiCeMqb/qAN9n0WIybBmhk8K7raZS/XppnstroLh2Y893/1lD2wj username@VM

  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ myResourceGroup }}"
      name: "{{  myVnet }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ mySubnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ myVnet }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ myResourceGroup }}"
      allocation_method: Static
      name: "{{ myPublicIP }}"
    register: output_ip_address

  - name: Create Network Security Group that allows SSH and port8080
    azure_rm_securitygroup:
      resource_group: "{{ myResourceGroup}}"
      name: "{{ myNetworkSecurityGroup }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
 
        - name: port8080
          protocol: Tcp
          destination_port_range: 8080
          access: Allow
          priority: 1000
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
     resource_group: "{{ myResourceGroup }}"
     name: "{{ myNIC }}"
     virtual_network: "{{ myVnet }}"
     subnet: "{{ mySubnet }}"
     public_ip_name: "{{ myPublicIP }}"
     security_group: "{{ myNetworkSecurityGroup }}"

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ myVM }}"
      vm_size: Standard_D2s_v3
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ mySSHkey }}"
      network_interfaces: "{{ myNIC }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest

  - name: Print Public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

